---
- name: Add cassandra apt key
  apt_key: url="http://debian.datastax.com/debian/repo_key"

- name: Add cassandra apt repository
  apt_repository: repo="deb http://debian.datastax.com/community/ stable main"

- name: Install cassandra
  apt: name="cassandra={{ spinnaker_cassandra_version }}" force=yes

- name: Install cassandra tools
  apt: name="cassandra-tools={{ spinnaker_cassandra_version }}"

- name: Wait for cassandra to start
  wait_for: port=7199

- name: Check if thrift is enabled for cassandra
  shell: nodetool statusthrift
  changed_when: false
  register: cassandra_thrift_status

- name: Enable thrift for cassandra
  shell: nodetool enablethrift
  when: "cassandra_thrift_status.stdout != 'running'"
