---
- name: Install Java 8
  apt: name=openjdk-8-jdk

- name: Install unzip
  apt: name=unzip

- name: Download packer
  get_url: dest=/tmp url="https://releases.hashicorp.com/packer/{{ spinnaker_packer_version }}/packer_{{ spinnaker_packer_version }}_linux_amd64.zip"

- name: Install packer
  unarchive: src=/tmp/packer_{{ spinnaker_packer_version }}_linux_amd64.zip dest=/usr/bin copy=no

- name: Install spinnaker
  apt: name=spinnaker
